### ISSUE TITLE
Gym.NET?

### ISSUE THREAD

**Issue by GeorgeS2019** [gilcoder/AI4U#7]
https://github.com/SciSharp/Gym.NET

FYI : the repository could benefit with a Godot client, in addition to WinForm and cross platform WPF.

Perhaps the framework could help you by pass the need of socket. Both AI and Game Engine in .NET?

**Comment by gilcoder** [comment]
> https://github.com/SciSharp/Gym.NET
> 
> FYI : the repository could benefit with a Godot client, in addition to WinForm and cross platform WPF.
> 
> Perhaps the framework could help you by pass the need of socket. Both AI and Game Engine in .NET?
It's an interesting idea. Do you have any use case suggestions? I will analyze how to integrate the two tools, although there is no deadline for this, as I have little time.

**Comment by GeorgeS2019** [comment]
@gilcoder  have a look at this: Godot Gym using ML.NET inference engine trained using PyTorch OpenAI Gym. It is interesting and curious to learn how the Godot part of AI4U, will fit into the project [here](https://github.com/JimFFM/ml-hackathon-2021/).

**Comment by gilcoder** [comment]
> @gilcoder have a look at this: Godot Gym using ML.NET inference engine trained using PyTorch OpenAI Gym. It is interesting and curious to learn how the Godot part of AI4U, will fit into the project [here](https://github.com/JimFFM/ml-hackathon-2021/).

The next version of AI4U will support ONNX models for both Unity and Godot. No longer added tool roadmap.
